<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Email</title>
<META http-equiv=Content-Type content=text/html;charset=utf-8>


</head>

<body style="MARGIN:20px 0px;BACKGROUND-COLOR: #FFFFFF;">
<!-- TABELLA DEL TEMPLATE -->
<table cellpadding="0" cellspacing="0" border="0" align="center" width="100%" style="HEIGHT: 100%;width:90%;border:2px solid #CEDED3;">
	<tr>
		<td style="WIDTH: 100%; HEIGHT: 1%;">
			   <!-- START HEADER-->
          <TABLE cellSpacing=0 cellPadding=0 width="100%" border="0">
            <TBODY>
            <TR>
              <TD width="1%" height="96" rowspan="2" style="background-color:#E2EBE4;"><IMG src="cid:logo" border=0 style="padding-left: 20px;"></TD>
              <TD style="background-color:#E2EBE4; FONT-WEIGHT: bold; FONT-SIZE: 12px; COLOR: #f6cd33; FONT-FAMILY: Verdana, Arial, Sans-Serif; text-align:right; padding-right:20px;" height="72px" width="99%">&nbsp;</TD>
           </TR>
           <TR>
              <TD style="background-color:#E2EBE4;FONT-SIZE: 8px;" width="99%">&nbsp;</TD>
           </TR>
           </TBODY>
          </TABLE>      
		</td>
	</tr>
	<tr>	
		<td>
			<table  cellSpacing=0 cellPadding=0 width="100%" border="0" style="background-color:#ffffff;">
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td style="vertical-align: top; text-align: left; background-color:#ffffff; font-family: Verdana, Arial, Sans-Serif; font-size:14px;">		  
					 	 
					 	TODO: Mail Text
			     	  
					</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
			</table>
		</td>	
	</tr>
	<tr>
		<td style="	WIDTH: 1%; HEIGHT: 1%;">

				<TABLE cellSpacing="0" cellPadding="0" width="100%" border="0">
				  <TR>
				    <TD style="text-align:left; VERTICAL-ALIGN:bottom; background-color:#ffffff;" width="1%"><IMG alt="" src="cid:left">
					 	<br>
					 	<br>
				    </TD>
				    <TD style="FONT-WEIGHT: normal; FONT-SIZE: 14px; COLOR: #000000; FONT-FAMILY: Verdana, Arial, Sans-Serif; text-align:center; background-color:#ffffff;" align="center"  width="48%">&nbsp;</TD>
				    <TD style="FONT-WEIGHT: normal; FONT-SIZE: 14px; COLOR: #000000; FONT-FAMILY: Verdana, Arial, Sans-Serif; text-align:center; background-color:#ffffff;"  width="2%" align="center">
             			<div style="WIDTH: 400px; padding: 10; background-color: #F4F4F4;  border: 1px solid #EEEEEE; FONT-FAMILY: Verdana, Arial, Sans-Serif; FONT-SIZE: 10px; margin-bottom: 5px;">This email is generated by an automated system, please do not respond.<div>
            		</TD>
            		<TD style="FONT-WEIGHT: normal; FONT-SIZE: 14px; COLOR: #000000; FONT-FAMILY: Verdana, Arial, Sans-Serif; text-align:center; background-color:#ffffff;" align="center"  width="48%">&nbsp;</TD>
				    <TD style="text-align:right; VERTICAL-ALIGN:bottom; background-color:#ffffff;" width="1%"><IMG alt="" src="cid:right"></TD>
				  </TR>
				</TABLE>    
				
		</td>
	</tr>
</table>
<!-- FINE TABELLA DEL TEMPLATE -->
</body>
</html>